# Generated by Django 3.0.2 on 2020-01-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankus_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consumer', models.CharField(blank=True, max_length=10)),
                ('mortgage', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
